### ISSUE TITLE
Peertube icon

### ISSUE THREAD

**Issue by just1602** [uiwjs/bootstrap-icons#17]
Hello,

I don't know if it is the right place to ask a new icon, but I was wondering if there was a chance to see a [Peertube](https://joinpeertube.org/) icon added to the set?

With all the hype around mastodon and the Fediverse, some people are starting to create Peertube channels and I thought it'd be nice to have an icon for this platform too.

Thanks in advance!

**Comment by jaywcjlove** [comment]
? add Peertube logo icon?
@just1602

**Comment by just1602** [comment]
I'd say yes, like the YouTube icon.
